server:
  port: 8091
spring:
  application:
    name: transfer-ntt
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb+srv://navlag:Fg3UgAroDl8SDVDt@avsavivd.lfqko.mongodb.net/pmactoob?retryWrites=true&w=majority
